### ISSUE TITLE
Longer samples are cut off in the playground

### ISSUE THREAD

**Issue by uncenter** [shikijs/textmate-grammars-themes#24]
Longer samples, like the one for Fortran (Fixed Form), are cut off due to an overflow/view height issue - and you can't scroll down in them either. I tried messing around with `overflow: auto` and `height` in Dev Tools but couldn't get it to work properly.

![Screenshot 2024-01-29 at 16 51 09 (Arc)](https://github.com/shikijs/textmate-grammars-themes/assets/47499684/a52db85b-5f4a-4657-adf4-ae79afda708d)

**Comment by antfu** [comment]
Should be fixed
