### ISSUE TITLE
Given a flag or scope name, how do I determine the file to load?

### ISSUE THREAD

**Issue by jameshfisher** [shikijs/textmate-grammars-themes#45]
I see the list of JSON files in `node_modules/tm-grammars/grammars`. When I load the right one, it works great. But how do I know which one to load?

I have what I think is called a "flag", from a Markdown fenced block, e.g. `"ts"`. From that, I somehow need to figure out to load `node_modules/tm-grammars/grammars/typescript.json`.

As an intermediate step, I need to find the scope name, which apparently is `"source.ts"`.

But I can't see how to do either step with this library. Can you provide an example?

**Comment by jameshfisher** [comment]
I see that `@wooorm/starry-night` provides `flagToScope`, which solves the first part, getting a scope name. But then I'm stuck knowing which file to load for a given scope name.

**Comment by antfu** [comment]
You have this file to resolve the alias: https://github.com/shikijs/textmate-grammars-themes/blob/a8df301a18feb707a85263275c4f92ec505d898f/packages/tm-grammars/index.js#L2595-L2597

**Comment by jameshfisher** [comment]
@antfu Aha, that helps, thanks! I ended up with these helper functions:

```ts
import * as tmGrammars from "tm-grammars";

function flagToGrammarInfo(flag: string) {
  return tmGrammars.grammars.find(
    (grammarInfo) =>
      flag === grammarInfo.name || grammarInfo.aliases?.includes(flag)
  );
}

function scopeNameToGrammarFilePath(scopeName: string) {
  for (const grammarInfo of tmGrammars.grammars) {
    if (scopeName === grammarInfo.scopeName) {
      return `./node_modules/tm-grammars/grammars/${grammarInfo.name}.json`;
    }
  }
}
```

**Comment by jameshfisher** [comment]
I think it would help to have an example like that in the README, but my problem is resolved so will close - thanks again!
