### ISSUE TITLE
Support conf lang

### ISSUE THREAD

**Issue by Mister-Hope** [shikijs/textmate-grammars-themes#70]
conf is a common extension in linux. And we already support `ini`, so adding a new alia named `conf` to it could be a nice enhancement?

Currently I am using langAlias to support it, but I think it might be worth built-in.

**Comment by antfu** [comment]
> conf is a common extension in linux

Do you have any reference to it? Is it safe to assume `x.conf` is in `ini` format? It sounds too general to know the language
