### ISSUE TITLE
angular inline template in angular-ts is broken

### ISSUE THREAD

**Issue by eneajaho** [shikijs/textmate-grammars-themes#72]
- Inline template is broken
- Inline styles are broken
- Class and other things don't show up correctly

![CleanShot 2024-07-20 at 18 58 32@2x](https://github.com/user-attachments/assets/4a6a151a-d29d-475f-827f-bf4431e3bc03)

**Comment by eneajaho** [comment]
Looks like `angular-inline-style.json` in line `23` has: ` "end": "(?=,|})",` but that `}` is messing with `}` in CSS for example: ```css
div { display: block; }
```

If we make it just: ` "end": "(?=,)",` it works fine, but only when we have `,` as the line ending which is not correct behavior IMO. 

This doesn't solve the HTML part which is not highlighted

**Comment by antfu** [comment]
The playground doesn't have the full injection capability (something to fix in the playground usage). But on Shiki it seems to work fine.

**Comment by eneajaho** [comment]
If that's the case, we can close this issue 🙌

**Comment by antfu** [comment]
It's still an issue of the playground tho, we could keep it open if someone wants to pick it up. Myself don't have the bandwidth to do it right now.
