### ISSUE TITLE
support protobuf

### ISSUE THREAD

**Issue by cruvie** [shikijs/textmate-grammars-themes#81]
the pr https://github.com/shikijs/shiki/pull/446/files seems reverted by accident

**Comment by antfu** [comment]
Would you send a quick PR to fix it? Thanks

**Comment by cruvie** [comment]
@antfu  Hi, thanks for your quick resp. I am more than happy to send a PR, but I'm not familiar with js, and I am not sure where to recommit the change mentioned in the pr above.
