### ISSUE TITLE
Use appropriate file extensions

### ISSUE THREAD

**Issue by RedCMD** [shikijs/textmate-grammars-themes#99]
TextMate grammars under [grammars](https://github.com/shikijs/textmate-grammars-themes/tree/main/packages/tm-grammars/grammars) and [raw](https://github.com/shikijs/textmate-grammars-themes/tree/main/packages/tm-grammars/raw) should use the official TextMate file extension `.tmLanguage.json` instead of the regular `.json` file extension

That way they get JSON TextMate syntax highlighting (VSCode)
![image](https://github.com/user-attachments/assets/1942efe4-faed-48b8-9597-3873c83e7d55)

Sample files under [samples](https://github.com/shikijs/textmate-grammars-themes/tree/main/samples) should use their respected language file extensions
![image](https://github.com/user-attachments/assets/49daf504-c867-47a3-9de1-6ff7aeb8ff5d)

**Comment by antfu** [comment]
- This is a repo that synchronize the grammars and themes, but not where you write them - while the syntax highlighting is something good to have, as it would require a lot effort to rewrite the script, I don't feel it's worth it.
- the `.sample` is on purpose to avoid IDE or automation tools that might change the content.

Thanks for bringing this up

**Comment by uncenter** [comment]
> the .sample is on purpose to avoid IDE or automation tools that might change the content.

I think this is a minor/rare issue and the benefit of having the samples properly syntax highlighted in editors and on GitHub outweighs that inconvenience. If you are open to the change happy to make a PR.
